### ISSUE TITLE
Newman script fails to run with reportportal

### ISSUE THREAD

**Issue by atmullan67** [reportportal/agent-js-postman#10]
Using the following options Newman collection fails to run, an exception is throw at the getTags method

newman run -r htmlextra,reportportal Smoke_Testing.postman_collection.json -e Swagger_Stage.post
man_environment.json --reporter-html-export --delay-request 5000 --reporter-reportportal-debug=true --reporter-reportpor
tal-endpoint=http://x.xx.xxx.xxx:8080/api/v1 --reporter-reportportal-token=xxxxx-xxxx-xxxx-xxxx --report
er-reportportal-launch=TEST_EXAMPLE --reporter-reportportal-project=project -x

Start launch g2pc9d9ojyof0zp7
Start test item g2pc9d9ojyof0zpi
Success start item g2pc9d9ojyof0zpi
C:\Users\Tony\AppData\Roaming\npm\node_modules\newman-reporter-reportportal\lib\index.js:179
            throw err;
            ^

TypeError: Cannot read property 'split' of null
    at getTags (C:\Users\Tony\AppData\Roaming\npm\node_modules\newman-reporter-reportportal\lib\index.js:365:34)
    at _.filter.flatMap.flatMap.forEach.stepName (C:\Users\Tony\AppData\Roaming\npm\node_modules\newman-reporter-reportportal\lib\index.js:147:27)
    at Array.forEach (<anonymous>)
    at EventEmitter.emitter.on (C:\Users\Tony\AppData\Roaming\npm\node_modules\newman-reporter-reportportal\lib\index.js:142:14)
    at EventEmitter.emit (C:\Users\Tony\AppData\Roaming\npm\node_modules\newman\node_modules\eventemitter3\index.js:203:33)
    at Function.callbacks.(anonymous function) [as beforeTest] (C:\Users\Tony\AppData\Roaming\npm\node_modules\newman\lib\run\index.js:194:34)
    at PostmanCollectionRun.event (C:\Users\Tony\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\runner\extensions\event.command.js:216:62)
    at Instruction.execute (C:\Users\Tony\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\runner\instruction.js:159:29)
    at PostmanCollectionRun._process (C:\Users\Tony\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\runner\run.js:168:21)
    at PostmanCollectionRun.<anonymous> (C:\Users\Tony\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\runner\run.js:169:76)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

**Comment by groov1kk** [comment]
Fixed
