### ISSUE TITLE
Request failed with status code 400 , using the latest version 5.0.2 newman-reporter-agent-js-postman

### ISSUE THREAD

**Issue by gregorygold** [reportportal/agent-js-postman#57]
newman run https://postman-echo.com/status/200 \
    -r @reportportal/agent-js-postman \
    --reporter-@reportportal/agent-js-postman-debug=true \
    --reporter-@reportportal/agent-js-postman-endpoint=https://reportportal.xxx.com/api/v1 \
    --reporter-@reportportal/agent-js-postman-token=xxxxxxxx-xxxxxxxx-xxxxxxxxxxx \
    --reporter-@reportportal/agent-js-postman-launch=superadmin_TEST_EXAMPLE \
    --reporter-@reportportal/agent-js-postman-project=lit-api \
    --reporter-@reportportal/agent-js-postman-description=TEST_LAUNCH \
    -x
Start launch sktwim4akrgtkbvj
Start test item sktwim4akrgtkc0o
Error start item sktwim4akrgtkc0o:
Error: **Request failed with status code 400**: {"errorCode":4001,"message":"Incorrect Request. [Field 'name' should not be null.] "}
    at /usr/local/lib/node_modules/@reportportal/newman-reporter-agent-js-postman/node_modules/@reportportal/client-javascript/lib/rest.js:36:23
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Request failed with status code 400: {"errorCode":4001,"message":"Incorrect Request. [Field 'name' should not be null.] "}
    at /usr/local/lib/node_modules/@reportportal/newman-reporter-agent-js-postman/node_modules/@reportportal/client-javascript/lib/rest.js:36:23
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Request failed with status code 400: {"errorCode":4001,"message":"Incorrect Request. [Field 'name' should not be null.] "}
    at /usr/local/lib/node_modules/@reportportal/newman-reporter-agent-js-postman/node_modules/@reportportal/client-javascript/lib/rest.js:36:23
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Request failed with status code 400: {"errorCode":4001,"message":"Incorrect Request. [Field 'name' should not be null.] "}
    at /usr/local/lib/node_modules/@reportportal/newman-reporter-agent-js-postman/node_modules/@reportportal/client-javascript/lib/rest.js:36:23
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by AmsterGet** [comment]
Hello @gregorygold !
It looks like the Report Portal was unable to find the test item name in the request. Are you sure it was provided?
It would be helpful if you could share more details on the structure of your tests.
